# Generated by Django 2.2.6 on 2019-12-28 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20191228_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete='model.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
