# Generated by Django 2.2.6 on 2019-12-28 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_auto_20191228_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answe',
            new_name='Answer',
        ),
    ]
