# Generated by Django 2.2.6 on 2020-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20191228_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
